language: go
go: 
  - "1.10"
env:
  global:
    - secure: "lJ0xVISyrceJ2K5nllxQpGMWzvKmuBDqsUbOFd33nytTg8L3WXOgYETGcvgTuIvfNR1Xeq/2T/0R1f5LaMivFsElQn+6UFMgn1qzJWGPRBJPKfhR8O/oRP4563AM1LsVCqBqG+Fx+EF7O/Z5tvPML5DQt2Scd8ZsAHnzeZYtN49vS5eA9axeEls5yWVhMXlV+4RKPHzo5fv3cUpjB/inYpT4As0nrpw7iunIEAMP6Ffow3FbjBzZQAy9dBBeN+tiNbHFbb2Qj+OcpZpAhChRDL5i83mph3Y7tafvEFriwxqLxiZmMlFGafHJYb/cdfI9cBXtjkCI1ezWufEcSqcjF/zJQ/AHS8AuzY0RN0oOHflQ/itSDjiXkTy4zMTagTAHxWdT71rs3fSzCn2tBOxnwFQrFm0pM6IbyhFh1jI5WBghzpTqn7VtNfVpGIj3fJUyiFkEWlVx9c5uUhtrGVhQJUNv3onSsvNkEXWHEexQZidZWC8inrKTVNzgN9DnZWaOvya1qPhPGb4hUqDtOANPVCfQ27QweU2yhqqDHV4lKHKkWAZJkAY/MRYviPyruf59rVXHYeJoZ1fBcTUVWpdDJKKRpYHkH4PO+E4fOB6zo3JdOGb2hxRJf7uywxRCLMzNl1wXWVe6MuXrg+eEdw73v4p8w2vJP0uru+N8Rzi7cx4="
    - "PATH=$GOPATH/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
script:
  - go test
after_success:
  - gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" -os="linux windows darwin" -arch="amd64 386"
  - ghr --username eclarke --token $GITHUB_TOKEN --replace --prerelease --debug latest dist/
